spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Mingliang520
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&userSSL=false
#    characterEncoding=utf-8&userSSL=false 防止中文乱码，以及协议安全性问题
#    url: jdbc:mysql://192.168.1.114/sell?characterEncoding=utf-8&userSSL=false
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  context-path: /sell
  port: 8080
wechat:
  mpAppId: wx6e4afca43ca02334
  mpAppSecret: 1b70f39a8e2c34746e0b8d33d4f126a1
#logging:
#  pattern:
#    console: "%d -%msg%n"
#  file: /sell.log
#  level:
#    com.lv.sell.LoggerTest: debug
##  path: /lvlog/
